"""empty message

Revision ID: 7223298c7406
Revises: 935a418e904a
Create Date: 2025-08-19 10:46:44.949238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7223298c7406'
down_revision: Union[str, Sequence[str], None] = '935a418e904a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_log', sa.Column('message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_log', 'message_id')
    # ### end Alembic commands ###
