"""Add payload to model answer log

Revision ID: 7bcdd120c8fb
Revises: af9c7aa43b96
Create Date: 2025-09-10 11:18:53.228728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcdd120c8fb'
down_revision: Union[str, Sequence[str], None] = 'af9c7aa43b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_model_answer_log', sa.Column('payload_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_model_answer_log', 'payload_json')
    # ### end Alembic commands ###
