"""Add FatSecret API cache tables

Revision ID: af9c7aa43b96
Revises: f7250d82aded
Create Date: 2025-09-10 08:23:46.861570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9c7aa43b96'
down_revision: Union[str, Sequence[str], None] = 'f7250d82aded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatsecret_food_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fatsecret_food_id', sa.String(length=100), nullable=False),
    sa.Column('food_name', sa.String(length=500), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('food_description', sa.Text(), nullable=True),
    sa.Column('food_type', sa.String(length=100), nullable=True),
    sa.Column('food_url', sa.String(length=1000), nullable=True),
    sa.Column('calories_per_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('protein_per_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fat_per_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('carbs_per_100g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('raw_api_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatsecret_food_id')
    )
    op.create_index('idx_brand_name', 'fatsecret_food_cache', ['brand_name'], unique=False)
    op.create_index('idx_food_id', 'fatsecret_food_cache', ['fatsecret_food_id'], unique=False)
    op.create_index('idx_food_name', 'fatsecret_food_cache', ['food_name'], unique=False)
    op.create_table('fatsecret_search_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_query', sa.String(length=500), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('api_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'fatsecret_search_cache', ['created_at'], unique=False)
    op.create_index('idx_search_query', 'fatsecret_search_cache', ['search_query'], unique=False)
    op.create_index('idx_search_type', 'fatsecret_search_cache', ['search_type'], unique=False)
    op.create_table('food_model_answer_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_answer', sa.String(), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=False),
    sa.Column('calories_kcal', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized'),
    sa.UniqueConstraint('name_normalized', name='uq_ingredient_name_normalized')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('food_model_answer_log')
    op.drop_index('idx_search_type', table_name='fatsecret_search_cache')
    op.drop_index('idx_search_query', table_name='fatsecret_search_cache')
    op.drop_index('idx_created_at', table_name='fatsecret_search_cache')
    op.drop_table('fatsecret_search_cache')
    op.drop_index('idx_food_name', table_name='fatsecret_food_cache')
    op.drop_index('idx_food_id', table_name='fatsecret_food_cache')
    op.drop_index('idx_brand_name', table_name='fatsecret_food_cache')
    op.drop_table('fatsecret_food_cache')
    # ### end Alembic commands ###
