"""empty message

Revision ID: f7250d82aded
Revises: 7223298c7406
Create Date: 2025-08-19 10:59:35.305429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7250d82aded'
down_revision: Union[str, Sequence[str], None] = '7223298c7406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_log', sa.Column('user_nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_log', 'user_nickname')
    # ### end Alembic commands ###
