"""Add api request call

Revision ID: f868b681d923
Revises: 7bcdd120c8fb
Create Date: 2025-09-10 11:21:33.408927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f868b681d923'
down_revision: Union[str, Sequence[str], None] = '7bcdd120c8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_model_answer_log', sa.Column('request_price', sa.Numeric(precision=12, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_model_answer_log', 'request_price')
    # ### end Alembic commands ###
